import { Info, TrendingUp, Brain, Shield, ExternalLink } from 'lucide-react'

export default function AboutPage() {
  return (
    <div>
      <div className="page-header">
        <h1>About This Project</h1>
        <p>How it works and important disclaimers</p>
      </div>

      <div className="card" style={{ marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
          <div style={{
            width: 42, height: 42, borderRadius: 10,
            background: 'rgba(79,109,255,0.15)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Brain size={20} color="var(--accent)" />
          </div>
          <h2 style={{ fontSize: 18, fontWeight: 700 }}>What Is This?</h2>
        </div>
        <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8 }}>
          This is a personal machine learning project built by Sammy Bolger. The goal is to use real NBA game data
          to train ML models that predict game outcomes, and then use those predictions to make data-backed,
          responsible gambling picks for fun. It pulls live game data from the BallDontLie API, computes rolling
          team statistics, and runs logistic regression models to estimate win probabilities for each matchup.
        </p>
      </div>

      <div className="card" style={{ marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
          <div style={{
            width: 42, height: 42, borderRadius: 10,
            background: 'rgba(255,159,67,0.15)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <TrendingUp size={20} color="var(--orange)" />
          </div>
          <h2 style={{ fontSize: 18, fontWeight: 700 }}>About the Moneylines</h2>
        </div>
        <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8 }}>
          The moneylines displayed on the Odds & Lines page are <strong style={{ color: '#fff' }}>not from real sportsbooks</strong>.
          They are computed directly from my model's predicted win probabilities using a standard probability-to-American-odds
          conversion. These are purely my model's predictions converted into a familiar moneyline format.
          They will obviously differ from actual sportsbook lines, which factor in things like public betting
          percentages, injury reports, and the book's own margin.
        </p>
      </div>

      <div className="card" style={{ marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
          <div style={{
            width: 42, height: 42, borderRadius: 10,
            background: 'rgba(255,77,106,0.15)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Shield size={20} color="var(--red)" />
          </div>
          <h2 style={{ fontSize: 18, fontWeight: 700 }}>Disclaimer</h2>
        </div>
        <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8, marginBottom: 12 }}>
          This project is for <strong style={{ color: '#fff' }}>informational and educational purposes only</strong>.
          Nothing on this site constitutes financial advice, betting advice, or a recommendation to place any wager.
          This is a personal ML project and should be treated as such. Always gamble responsibly and never bet
          more than you can afford to lose.
        </p>
        <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8 }}>
          The predictions here are generated by a relatively simple machine learning model. They are not guaranteed
          to be accurate and should not be relied upon as the sole basis for any betting decisions. Use your own
          judgment and do your own research.
        </p>
      </div>

      <div className="card" style={{ marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
          <div style={{
            width: 42, height: 42, borderRadius: 10,
            background: 'rgba(0,214,143,0.15)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Info size={20} color="var(--green)" />
          </div>
          <h2 style={{ fontSize: 18, fontWeight: 700 }}>How It Works</h2>
        </div>
        <ul style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 2.2, paddingLeft: 20 }}>
          <li>Game data is pulled from the BallDontLie API every 15 seconds during live games</li>
          <li>Rolling team stats (last 10 games) are computed: win %, points scored/allowed, net rating</li>
          <li>A logistic regression model is trained on historical game outcomes using these features</li>
          <li>Before each game, the model predicts each team's win probability</li>
          <li>Probabilities are converted to American moneyline format for easy reading</li>
          <li>You can pick one team per game before tipoff and track your record over time</li>
          <li>Picks are automatically graded when games finish</li>
        </ul>
      </div>

      <div style={{ textAlign: 'center', padding: '20px 0' }}>
        <a
          href="https://sammybolger.com"
          target="_blank"
          rel="noreferrer"
          style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            color: 'var(--accent)', fontSize: 14, textDecoration: 'none',
          }}
        >
          <ExternalLink size={14} />
          sammybolger.com
        </a>
      </div>
    </div>
  )
}
